name: Deploy via rsync para omeupredio.com

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout cÃ³digo
      uses: actions/checkout@v4

    - name: Criar chave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H cifrajam.com >> ~/.ssh/known_hosts

    - name: Deploy via rsync
      run: |
        rsync -az \
          --exclude=".env" \
          --exclude="/vendor/" \
          --exclude=".user.ini" \
          --exclude=".htaccess" \
          -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
          ./ \
          jamscroll@cifrajam.com:/home/rmcm/web/omeupredio.com/public_html/test

    - name: Composer install no servidor
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jamscroll@cifrajam.com << 'EOF'
          cd /home/rmcm/web/omeupredio.com/public_html/test
          export COMPOSER_ALLOW_SUPERUSER=1
          composer install --no-interaction --prefer-dist --optimize-autoloader
        EOF
